
deployUrl=file:///Users/cer/.m2/testdeploy

eventuateMavenRepoUrl=https://repo.maven.apache.org/maven2

springBootVersion=2.0.3.RELEASE
restAssuredVersion=2.9.0
springDependencyManagementPluginVersion=1.0.3.RELEASE
eventuateUtilVersion=0.9.0.RELEASE

dockerComposePluginVersion=0.14.2
micrometerVersion=1.0.4
