plugins {
    id "org.flywaydb.flyway" version "6.0.0"
}

flyway {
    url = "jdbc:mysql://${System.getenv('DOCKER_HOST_IP') ?: 'localhost'}/ftgo?useSSL=${System.getenv('DB_USE_SSL') ?: 'false'}"
    user = System.getenv('FLYWAY_USER') ?: 'root'
    password = System.getenv('FLYWAY_PASSWORD') ?: 'rootpassword'
    schemas = ['ftgo']
}
